/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'), assert = require('node:assert/strict'), ts = require('typescript');
for (const ext of ['.ts','.tsx']) require.extensions[ext] = (m,f) => m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,f);
require.extensions['.css'] = () => {};
const {JSDOM} = require('jsdom');
const dom = new JSDOM('<div id="root"></div>',{pretendToBeVisual:true,url:'https://esprit.test'});
for(const name of ['window','document','navigator','HTMLElement','HTMLTextAreaElement','HTMLInputElement','Element','Node','MutationObserver','localStorage','getComputedStyle','requestAnimationFrame','cancelAnimationFrame']) Object.defineProperty(global,name,{value:typeof dom.window[name]==='function' && ['getComputedStyle','requestAnimationFrame','cancelAnimationFrame'].includes(name)?dom.window[name].bind(dom.window):dom.window[name],configurable:true});
global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
const rt=require.resolve('../app/components/RichText.tsx');require.cache[rt]={id:rt,filename:rt,loaded:true,exports:{__esModule:true,default:({content})=>React.createElement('p',{className:'rich'},content)}};
const {default:Sheet,ReadToggle,radarDraft,notePreview}=require('../app/components/LibraryPaperSheet.tsx');
const {validatePdfReadingState}=require('../app/components/pdfReadingState.ts');
const tick=()=>new Promise(r=>setTimeout(r,10));
(async()=>{
  const radar={title:'Packets',authors:[],published:'',tldr:'',takeaways:['Tamaño óptimo'],why_relevant:'Sirve para la Fig. 3.',summary:'We compare two synthetic example datasets. More text.',project:'project-a',concrete_use:'',relevance_score:88,source_id:'x'};
  const tags=[{slug:'general',label:'Biblioteca general'},{slug:'project-a',label:'Proyecto A'},{slug:'project-b',label:'Proyecto B'}];
  let meta={collection:'project-a',tags:['project-a'],read:false,note:'',updated_ms:0,radar};
  const patches=[];
  const root=createRoot(document.getElementById('root'));
  const render=async()=>act(async()=>{root.render(React.createElement(Sheet,{meta,tags,label:(s)=>s,onUpdate:async(patch)=>{patches.push(patch);meta={...meta,...patch};await render();}}));await tick();});
  await render();
  assert.match(document.querySelector('.paper-idea').textContent,/We compare two synthetic example datasets\./,'without a tldr the radar idea falls back to the abstract');
  assert.match(document.querySelector('.paper-why').textContent,/Fig\. 3/,'what it is for, as the radar said');
  await act(async()=>{document.querySelector('.paper-tag-add').click();await tick();});
  await act(async()=>{[...document.querySelectorAll('.paper-tag-picker button')].find(b=>b.textContent.includes('Proyecto B')).click();await tick();});
  assert.deepEqual(patches.at(-1),{tags:['project-a','project-b']},'a paper can take several tags');
  await act(async()=>{document.querySelector('.paper-edit').click();await tick();});
  const area=document.querySelector('.paper-note-edit textarea');
  assert.equal(area.value,radarDraft(radar),'editing starts from what the radar said');
  assert.match(area.value,/- Tamaño óptimo/);
  await act(async()=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(area,'Mi nota: usar la **ec. 4**');area.dispatchEvent(new window.Event('input',{bubbles:true}));await tick();});
  await act(async()=>{[...document.querySelectorAll('.paper-note-edit button')].find(b=>b.textContent==='Guardar').click();await tick();});
  assert.deepEqual(patches.at(-1),{note:'Mi nota: usar la **ec. 4**'});
  assert.match(document.querySelector('.paper-summary .rich').textContent,/Mi nota/,'the note replaces the radar summary');
  assert.ok(document.querySelector('.paper-radar-original'),'and the original radar sheet stays folded below');
  assert.equal(notePreview('# Título\n**ec.** $N\\to\\infty$'),'Título');
  assert.equal(notePreview('usar **ec. 4** con $N$'),'usar ec. 4 con N');
  root.unmount();
  const root2=createRoot(document.getElementById('root'));let toggled=0;
  await act(async()=>{root2.render(React.createElement(ReadToggle,{read:false,onToggle:()=>toggled++}));await tick();});
  assert.equal(document.querySelector('.paper-read').textContent,'Sin leer');assert.equal(document.querySelector('.paper-read.read'),null);
  await act(async()=>{document.querySelector('.paper-read').click();await tick();});
  assert.equal(toggled,1);
  root2.unmount();
  assert.equal(validatePdfReadingState({page:3,scale:1,fit:'spread'})?.fit,'spread','the two-page mode is remembered per paper');
  dom.window.close();
  console.log('PASS: radar sheet with fallback idea, several tags, note seeded from the radar, read marker and remembered two-page mode.');
})().catch(e=>{console.error(e);process.exit(1);});
