/* eslint-disable @typescript-eslint/no-require-imports */
// Synthetic Markdown and DOM only; never opens a project or native bridge.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const ts = require('typescript');
for (const ext of ['.ts', '.tsx']) require.extensions[ext] = (module, file) => module._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText, file);
const { splitTableRow, findMarkdownTables } = require('../app/components/markdownTables.ts');
assert.deepEqual(splitTableRow('| $|ψ⟩$ | `a|b` | \\(|x|^2\\) | a\\|b |'), ['$|ψ⟩$', '`a|b`', '\\(|x|^2\\)', 'a|b']);
assert.deepEqual(splitTableRow('| A \\\\| B |'), ['A \\\\', 'B']);
assert.deepEqual(splitTableRow('| A \\\\\\| B |'), ['A \\\\| B']);
assert.deepEqual(splitTableRow('| \\$5 | value |'), ['\\$5', 'value']);
const { JSDOM } = require(process.env.ESPRIT_TEST_NODE_MODULES ? path.join(process.env.ESPRIT_TEST_NODE_MODULES, 'jsdom') : 'jsdom');
const dom = new JSDOM('<!doctype html><div id="editor"></div><div id="readonly"></div>', { pretendToBeVisual: true });
for (const name of ['window', 'document', 'navigator', 'HTMLElement', 'Element', 'Node', 'MutationObserver', 'DOMRect', 'getComputedStyle', 'requestAnimationFrame', 'cancelAnimationFrame']) Object.defineProperty(global, name, { value: typeof dom.window[name] === 'function' && ['getComputedStyle', 'requestAnimationFrame', 'cancelAnimationFrame'].includes(name) ? dom.window[name].bind(dom.window) : dom.window[name], configurable: true });
const { EditorState, EditorSelection } = require('@codemirror/state');
const { EditorView } = require('@codemirror/view');
const { livePreview } = require('../app/components/ScientificEditor.tsx');
const source = '# Note\n\n| Observable | Code | Explanation |\n| :--- | :---: | ---: |\n| $|x|^2$ | `a|b` | Long content remains one cell |\n| y | x |\n\nEnd';
const parsed = findMarkdownTables(source.split('\n'), () => false);
assert.equal(parsed.length, 1); assert.equal(parsed[0].header.length, 3); assert.equal(parsed[0].rows[0].length, 3);
const view = new EditorView({ parent: document.getElementById('editor'), state: EditorState.create({ doc: source, extensions: [livePreview({ current: {} })] }) });
const wrapper = view.dom.querySelector('.cm-md-table');
assert.equal(wrapper.style.getPropertyValue('--table-columns'), '3');
assert.equal(wrapper.querySelectorAll('th[scope="col"]').length, 3);
assert.equal(wrapper.querySelectorAll('tbody tr:first-child td').length, 3);
assert.equal(wrapper.querySelector('tbody tr:last-child td:last-child').textContent, '');
assert.equal(wrapper.querySelectorAll('th')[1].style.textAlign, 'center');
const caret = view.state.selection.main.head;
wrapper.querySelector('td').dispatchEvent(new window.MouseEvent('mousedown', { bubbles: true, button: 0 }));
assert.equal(view.state.selection.main.head, caret, 'Reading a cell does not replace its table with raw source');
wrapper.querySelector('.cm-md-table-edit').click();
assert.equal(view.state.selection.main.head, source.indexOf('| Observable'));
assert.equal(view.dom.querySelector('.cm-md-table'), null, 'Explicit edit opens exact source');
assert.equal(view.state.doc.toString(), source, 'Entering edit does not modify source');
view.dispatch({selection: EditorSelection.cursor(0)});
assert.ok(view.dom.querySelector('.cm-md-table'), 'Leaving the source restores its table');
const readonly = new EditorView({ parent: document.getElementById('readonly'), state: EditorState.create({ doc: source, extensions: [EditorState.readOnly.of(true), livePreview({ current: {} })] }) });
assert.equal(readonly.dom.querySelector('.cm-md-table-edit'), null);
view.destroy(); readonly.destroy(); dom.window.close();
console.log('PASS: scientific table delimiters, alignment, empty cells, stable reading and explicit lossless editing.');
